import { Component } from '@angular/core'
import { RouterLink, RouterLinkActive } from '@angular/router'
import {
  ReactiveFormsModule,
  FormBuilder,
  Validators,
  FormGroup,
} from '@angular/forms'
import { LibraryDBService } from '../db-service.service'

interface RegisterPayload {
  id: number
  name: string
  email: string
  phone: string
}

interface User {
  id: number
  name: string
  email: string
}

@Component({
  selector: 'app-auth',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, ReactiveFormsModule],
  templateUrl: './auth.component.html',
  styleUrl: './auth.component.css',
})
export class AuthComponent {
  error = ''
  user: User | null = null

  readonly registerForm: FormGroup
  readonly loginForm: FormGroup

  constructor(
    private fb: FormBuilder,
    private db: LibraryDBService
  ) {
    this.registerForm = this.fb.nonNullable.group({
      name: ['', [Validators.required, Validators.minLength(5)]],
      email: ['', [Validators.required, Validators.email]],
      phone: ['', [Validators.required, Validators.minLength(5)]],
    })

    this.loginForm = this.fb.nonNullable.group({
      email: ['', [Validators.required, Validators.email]],
      phone: ['', [Validators.required, Validators.minLength(5)]],
    })
  }

  async onRegister() {
    if (this.registerForm.invalid) return

    const payload: RegisterPayload = {
      id: Date.now(), // or generated by DB
      ...this.registerForm.getRawValue(),
    }

    try {
      await this.db.registerUser(payload)
      this.registerForm.reset()
      alert('Register success!')
    } catch (e: any) {
      this.error = e.message ?? 'Registration failed'
    }
  }

  async onLogin() {
    if (this.loginForm.invalid) return

    const { email, phone } = this.loginForm.getRawValue()

    try {
      this.user = await this.db.login(email, phone)
      this.error = ''
    } catch (e: any) {
      this.error = e.message ?? 'Login failed'
    }
  }
}